my_type=hypothesis
proj=yarn
u_test=org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list[1]=yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 9968891227
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 14103017111
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 18503216444
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 9354070020
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 18228860633
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 17619018427
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 10962435153
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 18972966228
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 17207351406
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 8573040708
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 13390330616
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 15016238822
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 9070565484
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 14203367810
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 12787837038
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 6996118904
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 13779448738
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 14295085094
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v2 running time = 8320676755
---> v1v2 test failed.
proj: yarn
u_test: org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
h_list: yarn.http.policy@@@yarn:ResourceManager@@@-3@@@HTTP_ONLY@@@HTTPS_ONLY
vv_mode: v1v2
result: FAIL
failureMessage: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
stackTrace: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: Invalid configuration! yarn.resourcemanager.hostname.rm1 or yarn.resourcemanager.webapp.https.address.rm1 needs to be set in an HA configuration.
	at org.apache.hadoop.yarn.conf.HAUtil.throwBadConfigurationException(HAUtil.java:45)
	at org.apache.hadoop.yarn.conf.HAUtil.checkAndSetRMRPCAddress(HAUtil.java:342)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetRMHAIdsList(HAUtil.java:130)
	at org.apache.hadoop.yarn.conf.HAUtil.verifyAndSetConfiguration(HAUtil.java:105)
	at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceInit(ResourceManager.java:284)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.initResourceManager(MiniYARNCluster.java:348)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$200(MiniYARNCluster.java:128)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceInit(MiniYARNCluster.java:497)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.service.CompositeService.serviceInit(CompositeService.java:108)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceInit(MiniYARNCluster.java:316)
	at org.apache.hadoop.service.AbstractService.init(AbstractService.java:164)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testProxyProvider(TestFederationRMFailoverProxyProvider.java:123)
	at org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider.testFederationRMFailoverProxyProvider(TestFederationRMFailoverProxyProvider.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v1v1 running time = 14983609431
updating test result for file org.apache.hadoop.yarn.client.TestFederationRMFailoverProxyProvider#testFederationRMFailoverProxyProvider
v2v2 running time = 14045980370
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 280
0
