my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list[1]=dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19357874846
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 19688952357
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 15500356543
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 19219786344
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 17844175737
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 21043915414
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 20727718256
---> v1v2 test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 26348783961
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 24018548056
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 27742378422
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 23421051184
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 18331055661
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 22962435302
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 23413119375
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 19185969814
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 20416237689
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 19397355801
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 19877556794
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 27353272880
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 21472697772
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 21660496376
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 26871715665
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-1@@@100s@@@0
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 19959850268
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 18502388665
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 8
v1v1v2v2 failed with probability 0 out of 8
Total execution time in seconds : 514
0
