my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list[1]=dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 30879141661
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 28111214336
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 31294522666
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 38316737570
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 35886111476
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 34246759081
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 31084823819
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 35632870659
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 37768464671
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 34666222401
---> v1v2 test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 33187614758
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 36816296944
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 28387984751
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 24027078226
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 25412681275
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 28037157120
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 22754815796
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 26575076683
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 31149780395
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 27488101999
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 26696215055
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v2 running time = 27138369597
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
h_list: dfs.ha.tail-edits.period.backoff-max@@@hdfs:NameNode@@@-2@@@0@@@100s
vv_mode: v1v2
result: FAIL
failureMessage: new checkpoint does not exist
stackTrace: java.lang.AssertionError: new checkpoint does not exist
	at org.junit.Assert.fail(Assert.java:88)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.verifyNNCheckpoint(TestRollingUpgrade.java:671)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpoint(TestRollingUpgrade.java:648)
	at org.apache.hadoop.hdfs.TestRollingUpgrade.testCheckpointWithMultipleNN(TestRollingUpgrade.java:571)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v1v1 running time = 20174483697
updating test result for file org.apache.hadoop.hdfs.TestRollingUpgrade#testCheckpointWithMultipleNN
v2v2 running time = 25302488287
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 8
v1v1v2v2 failed with probability 0 out of 8
Total execution time in seconds : 721
0
