my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list[1]=dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 311541643145
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 93899483096
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 35338409426
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 312422783018
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 99510281398
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 46082292961
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 313804174708
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 97647692017
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 39434842015
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 314618426488
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 98260661039
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 30503277832
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 319931731775
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 98398594826
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 40874260890
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 313477662009
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 107996202132
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 41342145921
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 318747481214
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@10
vv_mode: v1v2
result: FAIL
failureMessage: test timed out after 300000 milliseconds
stackTrace: org.junit.runners.model.TestTimedOutException: test timed out after 300000 milliseconds
	at java.lang.Thread.sleep(Native Method)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:508)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 117125233347
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 51332063214
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 3202
0
