my_type=hypothesis
proj=hdfs
u_test=org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list[1]=dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 83688038105
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 90891812886
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 160884414892
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 101277507388
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 88992379874
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 150825688323
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 90975427751
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 83487690202
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 123289927162
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 93130593914
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 83777515007
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 140158311839
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 88682949509
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 93356122587
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 150111133713
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 85636424625
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 93419481899
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 151012664694
---> v1v1 and v2v2 test test suceeded.
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v2 running time = 87125094910
---> v1v2 test failed.
proj: hdfs
u_test: org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
h_list: dfs.namenode.max-corrupt-file-blocks-returned@@@hdfs:NameNode@@@1@@@100@@@200
vv_mode: v1v2
result: FAIL
failureMessage: Namenode has 200 bad files. Expecting 100.
stackTrace: java.lang.AssertionError: Namenode has 200 bad files. Expecting 100.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks.testMaxCorruptFiles(TestListCorruptFileBlocks.java:515)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)


updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v1v1 running time = 96330965236
updating test result for file org.apache.hadoop.hdfs.server.namenode.TestListCorruptFileBlocks#testMaxCorruptFiles
v2v2 running time = 148872451789
---> v1v1 and v2v2 test test suceeded.
early stop after 7 is satisfied
v1v2 failed with probability 7 out of 7
v1v1v2v2 failed with probability 0 out of 7
Total execution time in seconds : 2285
0
